apiVersion: v1
kind: Service
metadata:
    name: "mytest-4d08"
    labels:
        app: "mytest-4d08"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "mytest-4d08"