on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: senpoc1.azurecr.io
        username: ${{ secrets.acr_senpoc1_username }}
        password: ${{ secrets.acr_senpoc1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t senpoc1.azurecr.io/poc:${{ github.sha }}
        docker push senpoc1.azurecr.io/poc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_poc_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep pocb85c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace pocb85c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: pocb85c
        container-registry-url: senpoc1.azurecr.io
        container-registry-username: ${{ secrets.acr_senpoc1_username }}
        container-registry-password: ${{ secrets.acr_senpoc1_password }}
        secret-name: pocdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: pocb85c
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          senpoc1.azurecr.io/poc:${{ github.sha }}
        imagepullsecrets: |
          pocdockerauth