# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  #  - name: Build with Maven
   #   run: mvn -B package --file pom.xml
    #- name: Build and Push Docker Image
     # uses: mr-smithers-excellent/docker-build-push@v4
      #with:
       # image: gopimohan2002/test
        #registry: docker.io
        #username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker build . -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/test:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/test:${{ github.sha }}
